language: node_js

if: commit_message !~ /(skip ci)/

node_js:
    - "node"

notifications:
    email:
      recipients:
        - filters@adguard.com
      on_success: never
      on_failure: always

install:
    - yarn install

script:
    - TLS=insecure node index.js; node validate.js; node validate-locales.js
